---
- name: Genarate host File
  hosts: lb01
  become: true
  gather_facts: true
  vars:
    my_file: /etc/keepalived/keepalived.conf
    my_template: templates/keepalive_master.j2
  tasks:
    - name: Install Keepalive
      yum: 
        name: keepalived
        state: latest
    - name: Stop Keepalive service
      service:
        name: keepalived
        state: stopped
    - name: Create "{{ my_file }}"
      template:
        src: "{{ my_template }}"
        dest: "{{ my_file }}"
        owner: root
        group: root
        mode: "0644"
    - name: start Keepalive service
      service:
        name: keepalived
        state: started